all: compile1 compile2 compile3

compile1:
	c++ -O3 -o test.x main.cpp planet.cpp solver.cpp -larmadillo -llapack -lblas
compile2:
	c++ -O3 -o test2.x main2.cpp planet.cpp solver.cpp -larmadillo -llapack -lblas
compile3:
	c++ -O3 -o test3.x main_esc_vel.cpp planet.cpp solver.cpp -larmadillo -llapack -lblas
