all: compile1 compile2 compile3 compile4

compile1:	
	c++ -O3 -o 1.x main.cpp planet.cpp solver.cpp -larmadillo -llapack -lblas
compile2:
	c++ -O3 -o 2.x main2.cpp planet.cpp solver.cpp -larmadillo -llapack -lblas
compile3:
	c++ -O3 -o 3.x main3.cpp planet.cpp solver.cpp -larmadillo -llapack -lblas
compile4:
	c++ -O3 -o 4.x main4.cpp planet.cpp solver.cpp -larmadillo -llapack -lblas
